version: "3.7"
services:
    neo4j:
        image: neo4j:3.5
        ports: 
            - "7474:7474"
            - "7373:7373"
            - "7687:7687"
        environment:
            - NEO4J_AUTH=none

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        command: mongod --replSet neomongo

    mongo_connector:
        build: ./mongo_connector
        links:
            - mongo
            - neo4j
        environment:
            - MONGO_HOST=mongo
            - NEO4J_HOST=neo4j